/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreaDoAssinanteRouteImport } from './routes/area-do-assinante'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as TermoDeResponsabilidadeRouteImport } from './routes/termo-de-responsabilidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaDoAssinanteRoute = AreaDoAssinanteRouteImport.update({
  id: '/area-do-assinante',
  path: '/area-do-assinante',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermoDeResponsabilidadeRoute = TermoDeResponsabilidadeRouteImport.update({
  id: '/termo-de-responsabilidade',
  path: '/termo-de-responsabilidade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area-do-assinante': typeof AreaDoAssinanteRoute
  '/blog': typeof BlogRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/lgpd': typeof LgpdRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/planos': typeof PlanosRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termo-de-responsabilidade': typeof TermoDeResponsabilidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-do-assinante': typeof AreaDoAssinanteRoute
  '/blog': typeof BlogRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/lgpd': typeof LgpdRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/planos': typeof PlanosRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termo-de-responsabilidade': typeof TermoDeResponsabilidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area-do-assinante': typeof AreaDoAssinanteRoute
  '/blog': typeof BlogRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/lgpd': typeof LgpdRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/planos': typeof PlanosRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termo-de-responsabilidade': typeof TermoDeResponsabilidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/area-do-assinante'
    | '/blog'
    | '/cobertura'
    | '/contato'
    | '/lgpd'
    | '/perguntas-frequentes'
    | '/planos'
    | '/politica-de-privacidade'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/termo-de-responsabilidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/area-do-assinante'
    | '/blog'
    | '/cobertura'
    | '/contato'
    | '/lgpd'
    | '/perguntas-frequentes'
    | '/planos'
    | '/politica-de-privacidade'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/termo-de-responsabilidade'
  id:
    | '__root__'
    | '/'
    | '/area-do-assinante'
    | '/blog'
    | '/cobertura'
    | '/contato'
    | '/lgpd'
    | '/perguntas-frequentes'
    | '/planos'
    | '/politica-de-privacidade'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/termo-de-responsabilidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaDoAssinanteRoute: typeof AreaDoAssinanteRoute
  BlogRoute: typeof BlogRoute
  CoberturaRoute: typeof CoberturaRoute
  ContatoRoute: typeof ContatoRoute
  LgpdRoute: typeof LgpdRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PlanosRoute: typeof PlanosRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreNosRoute: typeof SobreNosRoute
  TermoDeResponsabilidadeRoute: typeof TermoDeResponsabilidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-do-assinante': {
      id: '/area-do-assinante'
      path: '/area-do-assinante'
      fullPath: '/area-do-assinante'
      preLoaderRoute: typeof AreaDoAssinanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termo-de-responsabilidade': {
      id: '/termo-de-responsabilidade'
      path: '/termo-de-responsabilidade'
      fullPath: '/termo-de-responsabilidade'
      preLoaderRoute: typeof TermoDeResponsabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaDoAssinanteRoute: AreaDoAssinanteRoute,
  BlogRoute: BlogRoute,
  CoberturaRoute: CoberturaRoute,
  ContatoRoute: ContatoRoute,
  LgpdRoute: LgpdRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PlanosRoute: PlanosRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreNosRoute: SobreNosRoute,
  TermoDeResponsabilidadeRoute: TermoDeResponsabilidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
